### ISSUE TITLE
Consumer does not receive or process messages after automatic reconnect when connection lost

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/fedora-messaging#208]
Twice in the last little while I've had a consumer (using the systemd `fm-consumer@.service` consumer pattern) just stop processing messages at all. In both cases it seems the connection to the broker was lost and the consumer tried to reconnect. It claims to have done so successfully, but actually it never seems to process another message afterwards. Here's a log extract. Oct 08 00:06:26 is the last point at which it successfully consumes a message. Then the connection issue happens at 00:22:45. After that the consumer did not consume a single message until I noticed it was broken and restarted it at Oct 18 16:01:43. After the restart it immediately started picking up messages from the backlog that built up during the ten days it wasn't working - I included just the first in this extract.

    Oct 08 00:06:26 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO fedora_messaging.twisted.protocol] Consuming message from topic org.fedoraproject.prod.pungi.compose.status.change (message id 2019-72b3456e-431c-461e-a61e-22a4847b2a46)
    Oct 08 00:06:26 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO fedora_messaging.twisted.protocol] Successfully consumed message from topic org.fedoraproject.prod.pungi.compose.status.change (message id 2019-72b3456e-431c-461e-a61e-22a4847b2a46)
    Oct 08 00:22:45 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [WARNING fedora_messaging.twisted.protocol] The connection to the broker was lost (ConnectionDone()), consumer halted; the connection should restart and consuming will resume.
    Oct 08 00:22:45 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO twisted] <twisted.internet.tcp.Connector instance at 0x7f32b8a8ddd0 disconnected IPv4Address(type='TCP', host='rabbitmq.fedoraproject.org', port=5671)> will retry in 2 seconds
    Oct 08 00:22:45 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO twisted] Stopping factory FedoraMessagingFactoryV2(parameters=<URLParameters host=rabbitmq.fedoraproject.org port=5671 virtual_host=/pubsub ssl=True>, confirms=True)
    Oct 08 00:22:45 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO fedora_messaging.twisted.protocol] Disconnect requested, but AMQP connection already gone
    Oct 08 00:22:47 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO twisted] Starting factory FedoraMessagingFactoryV2(parameters=<URLParameters host=rabbitmq.fedoraproject.org port=5671 virtual_host=/pubsub ssl=True>, confirms=True)
    Oct 08 00:22:47 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO fedora_messaging.twisted.factory] Re-registering the Consumer(queue=openqa_relvalconsumer, callback=<relvalconsumer.RelvalConsumer object at 0x7f32bab8e510>) consumer
    Oct 08 00:22:47 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO fedora_messaging.twisted.protocol] Successfully registered AMQP consumer Consumer(queue=openqa_relvalconsumer, callback=<relvalconsumer.RelvalConsumer object at 0x7f32bab8e510>)
    Oct 08 00:24:55 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [WARNING fedora_messaging.twisted.protocol] The connection to the broker was lost (ConnectionDone()), consumer halted; the connection should restart and consuming will resume.
    Oct 08 00:24:55 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO twisted] <twisted.internet.tcp.Connector instance at 0x7f32b8a8ddd0 disconnected IPv4Address(type='TCP', host='rabbitmq.fedoraproject.org', port=5671)> will retry in 3 seconds
    Oct 08 00:24:55 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO twisted] Stopping factory FedoraMessagingFactoryV2(parameters=<URLParameters host=rabbitmq.fedoraproject.org port=5671 virtual_host=/pubsub ssl=True>, confirms=True)
    Oct 08 00:24:55 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO fedora_messaging.twisted.protocol] Disconnect requested, but AMQP connection already gone
    Oct 08 00:24:58 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO twisted] Starting factory FedoraMessagingFactoryV2(parameters=<URLParameters host=rabbitmq.fedoraproject.org port=5671 virtual_host=/pubsub ssl=True>, confirms=True)
    Oct 08 00:24:58 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO fedora_messaging.twisted.factory] Re-registering the Consumer(queue=openqa_relvalconsumer, callback=<relvalconsumer.RelvalConsumer object at 0x7f32bab8e510>) consumer
    Oct 08 00:24:58 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO fedora_messaging.twisted.protocol] Successfully registered AMQP consumer Consumer(queue=openqa_relvalconsumer, callback=<relvalconsumer.RelvalConsumer object at 0x7f32bab8e510>)
    Oct 18 16:01:43 openqa01.qa.fedoraproject.org systemd[1]: Stopping Fedora Messaging consumer...
    Oct 18 16:01:44 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO twisted] Received SIGTERM, shutting down.
    Oct 18 16:01:44 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO fedora_messaging.twisted.protocol] Waiting for 1 consumer(s) to finish processing before halting
    Oct 18 16:01:51 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO fedora_messaging.cli] The Consumer(queue=openqa_relvalconsumer, callback=<relvalconsumer.RelvalConsumer object at 0x7f32bab8e510>) consumer halted.
    Oct 18 16:01:51 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO fedora_messaging.cli] All consumers have stopped; shutting down.
    Oct 18 16:01:51 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO fedora_messaging.twisted.protocol] Finished canceling 0 consumers
    Oct 18 16:01:54 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO twisted] Stopping factory FedoraMessagingFactoryV2(parameters=<URLParameters host=rabbitmq.fedoraproject.org port=5671 virtual_host=/pubsub ssl=True>, confirms=True)
    Oct 18 16:01:54 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO fedora_messaging.twisted.protocol] Disconnect requested, but AMQP connection already gone
    Oct 18 16:01:54 openqa01.qa.fedoraproject.org fedora-messaging[15817]: [INFO twisted] Main loop terminated.
    Oct 18 16:02:13 openqa01.qa.fedoraproject.org systemd[1]: fm-consumer@relvalconsumer.service: Succeeded.
    Oct 18 16:02:13 openqa01.qa.fedoraproject.org systemd[1]: Stopped Fedora Messaging consumer.
    Oct 18 16:02:13 openqa01.qa.fedoraproject.org systemd[1]: Started Fedora Messaging consumer.
    Oct 18 16:02:17 openqa01.qa.fedoraproject.org fedora-messaging[22384]: [INFO fedora_messaging.cli] Starting consumer with relvalconsumer:RelvalConsumer callback
    Oct 18 16:02:18 openqa01.qa.fedoraproject.org fedora-messaging[22384]: [INFO fedora_messaging._session] Authenticating with server using x509 (certfile: /etc/pki/fedora-messaging/openqa-cert.pem, keyfile: /etc/pki/fedora-messaging/openqa-key.pem)
    Oct 18 16:02:18 openqa01.qa.fedoraproject.org fedora-messaging[22384]: [INFO twisted] Starting factory FedoraMessagingFactoryV2(parameters=<URLParameters host=rabbitmq.fedoraproject.org port=5671 virtual_host=/pubsub ssl=True>, confirms=True)
    Oct 18 16:02:18 openqa01.qa.fedoraproject.org fedora-messaging[22384]: [INFO fedora_messaging.twisted.protocol] Successfully registered AMQP consumer Consumer(queue=openqa_relvalconsumer, callback=<relvalconsumer.RelvalConsumer object at 0x7fcd2fc59650>)
    Oct 18 16:02:18 openqa01.qa.fedoraproject.org fedora-messaging[22384]: [INFO fedora_messaging.message] Registering the 'base.message' key as the '<class 'fedora_messaging.message.Message'>' class in the Message class registry
    Oct 18 16:02:18 openqa01.qa.fedoraproject.org fedora-messaging[22384]: [INFO fedora_messaging.twisted.protocol] Consuming message from topic org.fedoraproject.prod.pungi.compose.status.change (message id 2019-8999933d-4a86-42e3-82dc-8691891d834a)

**Comment by AdamWill** [comment]
So I had another case of this on openqa production, the resultsdb reporting consumer broke which meant no openqa results got forwarded to resultsdb for a week:

    Nov 06 22:10:12 openqa01.qa.fedoraproject.org fedora-messaging[10720]: [INFO fedora_messaging.twisted.protocol] Successfully consumed message from topic org.fedoraproject.prod.openqa.job.done (message id d3bc8c2f-97ff-41c9-9f43-e1ad2d9ff956)
    Nov 06 22:10:13 openqa01.qa.fedoraproject.org fedora-messaging[10720]: [ERROR fedora_messaging.twisted.protocol] An unexpected AMQP error occurred; the connection should restart, but please report this as a bug.
    Nov 06 22:10:13 openqa01.qa.fedoraproject.org fedora-messaging[10720]: Traceback (most recent call last):
    Nov 06 22:10:13 openqa01.qa.fedoraproject.org fedora-messaging[10720]:   File "/usr/lib64/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    Nov 06 22:10:13 openqa01.qa.fedoraproject.org fedora-messaging[10720]:     result = g.send(result)
    Nov 06 22:10:13 openqa01.qa.fedoraproject.org fedora-messaging[10720]:   File "/usr/lib/python3.7/site-packages/fedora_messaging/twisted/protocol.py", line 277, in _read
    Nov 06 22:10:13 openqa01.qa.fedoraproject.org fedora-messaging[10720]:     yield channel.basic_ack(delivery_tag=delivery_frame.delivery_tag)
    Nov 06 22:10:13 openqa01.qa.fedoraproject.org fedora-messaging[10720]:   File "/usr/lib/python3.7/site-packages/pika/adapters/twisted_connection.py", line 338, in basic_ack
    Nov 06 22:10:13 openqa01.qa.fedoraproject.org fedora-messaging[10720]:     delivery_tag=delivery_tag, multiple=multiple)
    Nov 06 22:10:13 openqa01.qa.fedoraproject.org fedora-messaging[10720]:   File "/usr/lib/python3.7/site-packages/pika/channel.py", line 202, in basic_ack
    Nov 06 22:10:13 openqa01.qa.fedoraproject.org fedora-messaging[10720]:     self._raise_if_not_open()
    Nov 06 22:10:13 openqa01.qa.fedoraproject.org fedora-messaging[10720]:   File "/usr/lib/python3.7/site-packages/pika/channel.py", line 1389, in _raise_if_not_open
    Nov 06 22:10:13 openqa01.qa.fedoraproject.org fedora-messaging[10720]:     raise exceptions.ChannelWrongStateError('Channel is closed.')
    Nov 06 22:10:13 openqa01.qa.fedoraproject.org fedora-messaging[10720]: pika.exceptions.ChannelWrongStateError: Channel is closed.
    Nov 06 22:10:14 openqa01.qa.fedoraproject.org fedora-messaging[10720]: [INFO fedora_messaging.twisted.protocol] Successfully consumed message from topic org.fedoraproject.prod.openqa.job.done (message id d3bc8c2f-97ff-41c9-9f43-e1ad2d9ff956)
    Nov 06 22:10:14 openqa01.qa.fedoraproject.org fedora-messaging[10720]: [INFO fedora_messaging.twisted.protocol] Consuming message from topic org.fedoraproject.prod.openqa.job.done (message id 5fdd96d9-acff-4a72-9eb4-2627efce0c34)
    Nov 06 22:10:14 openqa01.qa.fedoraproject.org fedora-messaging[10720]: [INFO OpenQAResultsDBReporter] reporting results for 481218
    Nov 06 22:10:16 openqa01.qa.fedoraproject.org fedora-messaging[10720]: [INFO fedora_messaging.twisted.protocol] Successfully consumed message from topic org.fedoraproject.prod.openqa.job.done (message id 5fdd96d9-acff-4a72-9eb4-2627efce0c34)
    Nov 06 22:10:24 openqa01.qa.fedoraproject.org fedora-messaging[10720]: [INFO fedora_messaging.twisted.protocol] Consuming message from topic org.fedoraproject.prod.openqa.job.done (message id 45e26ad7-2591-407c-9596-b3a50319ffed)
    Nov 06 22:10:24 openqa01.qa.fedoraproject.org fedora-messaging[10720]: [INFO OpenQAResultsDBReporter] reporting results for 481212
    Nov 06 22:10:25 openqa01.qa.fedoraproject.org fedora-messaging[10720]: [INFO fedora_messaging.twisted.protocol] Successfully consumed message from topic org.fedoraproject.prod.openqa.job.done (message id 45e26ad7-2591-407c-9596-b3a50319ffed)
    Nov 06 22:12:11 openqa01.qa.fedoraproject.org fedora-messaging[10720]: [INFO fedora_messaging.twisted.protocol] Consuming message from topic org.fedoraproject.prod.openqa.job.done (message id 62dae522-8e6a-4d8e-a6b2-d3c3ba005e2f)
    Nov 06 22:12:11 openqa01.qa.fedoraproject.org fedora-messaging[10720]: [INFO OpenQAResultsDBReporter] reporting results for 481213
    Nov 06 22:12:14 openqa01.qa.fedoraproject.org fedora-messaging[10720]: [INFO fedora_messaging.twisted.protocol] Successfully consumed message from topic org.fedoraproject.prod.openqa.job.done (message id 62dae522-8e6a-4d8e-a6b2-d3c3ba005e2f)
    Nov 13 17:33:03 openqa01.qa.fedoraproject.org systemd[1]: Stopping Fedora Messaging consumer...

so it hit a traceback, somehow a few more results were forwarded for the next couple of minutes, but then it did nothing at all until I manually restarted it a week later. After the restart it started forwarded all the results it had missed in the last week.

If you think this is fixed upstream now, what needs doing so my production consumers do not constantly break? Does the server end need updating? Do we need to ship updates for the client code in Fedora packages?

**Comment by AdamWill** [comment]
Also note that F30 - where I'm seeing this - has fedora-messaging 1.7.2, and this code is different there, because there was commit 23a8df26d5bac69c89bfe9739bb760ed155e6375 on master in the meantime which changed this and makes the fix not obviously backportable at all.

**Comment by AdamWill** [comment]
@abompard ping re ^^^
