### ISSUE TITLE
Unhandled error and failing to reconnect

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/fedora-messaging#221]
This is the second time we're observing that situation in the Fedora Infrastructure which leads to the consumers being stuck and stopping to process their messages.

Here is the traceback:
````
 Traceback (most recent call last):
   File "/usr/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
     result = g.send(result)
 StopIteration
 [INFO twisted] <twisted.internet.tcp.Connector instance at 0x7fe95ad6b4e0 disconnected IPv4Address(type='TCP', host='rabbitmq.fedoraproject.org', port=5671)> will retry in 2 seconds
 [INFO twisted] Stopping factory FedoraMessagingFactoryV2(parameters=<URLParameters host=rabbitmq.fedoraproject.org port=5671 virtual_host=/pubsub ssl=True>, confirms=True)
 [INFO fedora_messaging.twisted.protocol] Disconnect requested, but AMQP connection already gone
 [INFO twisted] Starting factory FedoraMessagingFactoryV2(parameters=<URLParameters host=rabbitmq.fedoraproject.org port=5671 virtual_host=/pubsub ssl=True>, confirms=True)
 [ERROR pika.adapters.twisted_connection] connection_lost: ConnectionLost('Connection lost',)
 Unhandled error in Deferred:
 [CRITICAL twisted] Unhandled error in Deferred:
 Traceback (most recent call last):
   File "/usr/lib/python3.6/site-packages/pika/callback.py", line 233, in process
     callback(*args, **keywords)
   File "/usr/lib/python3.6/site-packages/pika/adapters/twisted_connection.py", line 1240, in _on_connection_failed
     d.errback(exc)
   File "/usr/lib64/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
     self._startRunCallbacks(fail)
   File "/usr/lib64/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
     self._runCallbacks()
 --- <exception caught here> ---
   File "/usr/lib64/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
     current.result = callback(current.result, *args, **kw)
   File "/usr/lib/python3.6/site-packages/fedora_messaging/twisted/factory.py", line 337, in on_ready_errback
     self._client_deferred.errback(wrapped_failure)
   File "/usr/lib64/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
     self._startRunCallbacks(fail)
   File "/usr/lib64/python3.6/site-packages/twisted/internet/defer.py", line 561, in _startRunCallbacks
     raise AlreadyCalledError
 twisted.internet.defer.AlreadyCalledError:
 [CRITICAL twisted]
 Traceback (most recent call last):
   File "/usr/lib64/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
     current.result = callback(current.result, *args, **kw)
   File "/usr/lib/python3.6/site-packages/fedora_messaging/twisted/factory.py", line 337, in on_ready_errback
     self._client_deferred.errback(wrapped_failure)
   File "/usr/lib64/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
     self._startRunCallbacks(fail)
   File "/usr/lib64/python3.6/site-packages/twisted/internet/defer.py", line 561, in _startRunCallbacks
     raise AlreadyCalledError
 twisted.internet.defer.AlreadyCalledError
 [INFO twisted] <twisted.internet.tcp.Connector instance at 0x7fe95ad6b4e0 disconnected IPv4Address(type='TCP', host='rabbitmq.fedoraproject.org', port=5671)> will retry in 7 seconds
 [INFO twisted] Stopping factory FedoraMessagingFactoryV2(parameters=<URLParameters host=rabbitmq.fedoraproject.org port=5671 virtual_host=/pubsub ssl=True>, confirms=True)
 [INFO fedora_messaging.twisted.protocol] Disconnect requested, but AMQP connection already gone
 [INFO twisted] Starting factory FedoraMessagingFactoryV2(parameters=<URLParameters host=rabbitmq.fedoraproject.org port=5671 virtual_host=/pubsub ssl=True>, confirms=True)
 [ERROR fedora_messaging.twisted.factory] The connection failed with an unexpected exception; please report this bug.
 Traceback (most recent call last):
   File "/usr/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
     result = g.send(result)
 StopIteration
````

**Comment by abompard** [comment]
Yep, `AlreadyCalledError` should never happen. Which version of Fedora Messaging is this?

**Comment by pypingou** [comment]
That specific traceback was on batcave01 so RHEL8 and I've seen a shorter version of this traceback but with the same end error ("StopIteration") on the greenwave container which seems to be running F29 (fedora-messaging-1.7.1-1.fc29.noarch says rpm -q)

**Comment by jeremycline** [comment]
> That specific traceback was on batcave01 so RHEL8 and I've seen a shorter version of this traceback but with the same end error ("StopIteration") on the greenwave container which seems to be running F29 (fedora-messaging-1.7.1-1.fc29.noarch says rpm -q)

StopIteration is just part of the iterator interface in Python, it has nothing to do with the actual problem. If I recall correctly, @abompard fixed this a long time ago, but it may only be in 2.0+. There are very minor API differences so upgrading should be easy. Obviously, Fedora 29 is unsupported so there's not much we can do there. Since you didn't actually mention what version of fedora-messaging you were using on RHEL8 I have no idea about that.

**Comment by pypingou** [comment]
Looks like RHEL8 has the same version ``fedora-messaging-1.7.1-2.el8.noarch``

**Comment by pypingou** [comment]
Looks like there is a 2.0.1 build in epel8 let's try it: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-28f4d1b799

**Comment by pypingou** [comment]
I've updated fedora-messaging on batcave we'll see if that helps

**Comment by pypingou** [comment]
Let's close this ticket and re-open and if see it again, no need to have it linger.

Thanks for your help!
